# Docker Compose for local development with cloud databases
# This is a simplified version that only runs the API service
# All databases (Supabase, Qdrant, MongoDB) are hosted in the cloud

version: "3.8"

services:
  youtube-recommendation-api:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - .:/app # Mount source code for development (optional)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Uncomment for development with code hot-reloading
    command:
      [
        "uvicorn",
        "backend.api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--reload",
      ]
